default_stages: [pre-commit]
repos:
  # Ruff formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        name: Linting (Ruff)
        args: [--fix]
        files: \.py$
      - id: ruff-format
        name: Formatting (Ruff)
        files: \.py$

  # Commit message valudation
  - repo: local
    hooks:
      - id: validate-commit-message
        name: Commit message validation
        entry: python tools/validate-commit-message.py
        language: system
        stages: [commit-msg]
